package dev.mackerel.d1jdbc;

import dev.mackerel.d1jdbc.transport.Capabilities;
import dev.mackerel.d1jdbc.transport.D1QueryResult;
import dev.mackerel.d1jdbc.transport.D1Request;
import dev.mackerel.d1jdbc.transport.D1Transport;
import dev.mackerel.d1jdbc.transport.TransportException;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

/**
 * JDBC {@link Connection} over a {@link D1Transport}.
 *
 * <p>D1 has no interactive transactions (DESIGN section 5). With
 * {@code autoCommit=true} each statement is sent immediately. With
 * {@code autoCommit=false}, mutating statements are buffered and flushed on
 * {@link #commit()} as a single {@link D1Transport#batch batch} (atomic on the
 * proxy transport, best-effort on REST); {@link #rollback()} discards the
 * buffer. The connection carries the latest session bookmark
 * ({@code x-d1-bookmark}) for read-your-write consistency.
 */
public final class D1Connection implements Connection {

    private final D1JdbcUrl url;
    private final D1Transport transport;
    private final List<D1Request> buffer = new ArrayList<>();

    private boolean autoCommit = true;
    private boolean closed = false;
    private boolean readOnly = false;
    private String bookmark;
    private SQLWarning warnings;

    public D1Connection(D1JdbcUrl url, D1Transport transport) {
        this.url = url;
        this.transport = transport;
    }

    // ------------------------------------------------------ package internals

    D1Transport transport() {
        return transport;
    }

    D1JdbcUrl url() {
        return url;
    }

    Capabilities capabilities() {
        return transport.capabilities();
    }

    String bookmark() {
        return bookmark;
    }

    /** Update the session bookmark from a transport response. */
    void updateBookmark(String newBookmark) {
        if (newBookmark != null && !newBookmark.isEmpty()) {
            this.bookmark = newBookmark;
        }
    }

    /**
     * Buffer a mutating statement when {@code autoCommit=false}. Flushed as a
     * single atomic batch on {@link #commit()}.
     */
    void bufferStatement(String sql, List<Object> params) {
        buffer.add(new D1Request(sql, new ArrayList<>(params)));
    }

    boolean isAutoCommitInternal() {
        return autoCommit;
    }

    void checkOpen() throws SQLException {
        if (closed) {
            throw new SQLException("Connection is closed", "08003");
        }
    }

    // ------------------------------------------------------------- statements

    @Override
    public Statement createStatement() throws SQLException {
        checkOpen();
        return new D1Statement(this);
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        checkOpen();
        return new D1PreparedStatement(this, sql);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency)
            throws SQLException {
        checkOpen();
        return new D1Statement(this);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType,
            int resultSetConcurrency) throws SQLException {
        checkOpen();
        return new D1PreparedStatement(this, sql);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency,
            int resultSetHoldability) throws SQLException {
        checkOpen();
        return new D1Statement(this);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType,
            int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        checkOpen();
        return new D1PreparedStatement(this, sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys)
            throws SQLException {
        checkOpen();
        return new D1PreparedStatement(this, sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes)
            throws SQLException {
        checkOpen();
        return new D1PreparedStatement(this, sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames)
            throws SQLException {
        checkOpen();
        return new D1PreparedStatement(this, sql);
    }

    @Override
    public CallableStatement prepareCall(String sql) throws SQLException {
        throw new SQLFeatureNotSupportedException("D1 does not support stored procedures");
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency)
            throws SQLException {
        throw new SQLFeatureNotSupportedException("D1 does not support stored procedures");
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency,
            int resultSetHoldability) throws SQLException {
        throw new SQLFeatureNotSupportedException("D1 does not support stored procedures");
    }

    @Override
    public String nativeSQL(String sql) throws SQLException {
        checkOpen();
        return sql;
    }

    // ---------------------------------------------------------- transactions

    @Override
    public void setAutoCommit(boolean autoCommit) throws SQLException {
        checkOpen();
        if (this.autoCommit == autoCommit) {
            return;
        }
        // Switching to auto-commit flushes any pending buffered work.
        if (autoCommit && !buffer.isEmpty()) {
            commit();
        }
        this.autoCommit = autoCommit;
    }

    @Override
    public boolean getAutoCommit() throws SQLException {
        checkOpen();
        return autoCommit;
    }

    @Override
    public void commit() throws SQLException {
        checkOpen();
        if (autoCommit) {
            throw new SQLException("commit() called while in auto-commit mode", "25000");
        }
        if (buffer.isEmpty()) {
            return;
        }
        List<D1Request> toSend = new ArrayList<>(buffer);
        buffer.clear();
        if (toSend.size() > 1 && !transport.capabilities().supportsAtomicBatch()) {
            // DESIGN 5: REST cannot run an atomic multi-statement batch. The
            // Connection contract implies atomicity, so warn rather than silently
            // apply statements one-by-one with no rollback on partial failure.
            addWarning(new SQLWarning("Transport '"
                    + transport.capabilities().transportName()
                    + "' does not support atomic batches; the " + toSend.size()
                    + " buffered statement(s) are applied sequentially and will not be"
                    + " rolled back if one fails midway.", "01000"));
        }
        try {
            List<D1QueryResult> results = transport.batch(toSend, bookmark);
            for (D1QueryResult r : results) {
                updateBookmark(r.bookmark());
            }
        } catch (TransportException e) {
            throw D1Codec.toSQLException(e);
        }
    }

    @Override
    public void rollback() throws SQLException {
        checkOpen();
        if (autoCommit) {
            throw new SQLException("rollback() called while in auto-commit mode", "25000");
        }
        buffer.clear();
    }

    @Override
    public Savepoint setSavepoint() throws SQLException {
        throw new SQLFeatureNotSupportedException("D1 does not support savepoints");
    }

    @Override
    public Savepoint setSavepoint(String name) throws SQLException {
        throw new SQLFeatureNotSupportedException("D1 does not support savepoints");
    }

    @Override
    public void rollback(Savepoint savepoint) throws SQLException {
        throw new SQLFeatureNotSupportedException("D1 does not support savepoints");
    }

    @Override
    public void releaseSavepoint(Savepoint savepoint) throws SQLException {
        throw new SQLFeatureNotSupportedException("D1 does not support savepoints");
    }

    // ---------------------------------------------------------------- state

    @Override
    public void close() throws SQLException {
        if (closed) {
            return;
        }
        closed = true;
        buffer.clear();
        transport.close();
    }

    @Override
    public boolean isClosed() {
        return closed;
    }

    @Override
    public DatabaseMetaData getMetaData() throws SQLException {
        checkOpen();
        return new D1DatabaseMetaData(this);
    }

    @Override
    public void setReadOnly(boolean readOnly) throws SQLException {
        checkOpen();
        this.readOnly = readOnly;
    }

    @Override
    public boolean isReadOnly() throws SQLException {
        checkOpen();
        return readOnly;
    }

    @Override
    public void setCatalog(String catalog) throws SQLException {
        checkOpen();
        // D1 has no catalog concept; ignored.
    }

    @Override
    public String getCatalog() throws SQLException {
        checkOpen();
        return null;
    }

    @Override
    public void setSchema(String schema) throws SQLException {
        checkOpen();
        // D1 has no schema concept; ignored.
    }

    @Override
    public String getSchema() throws SQLException {
        checkOpen();
        return null;
    }

    @Override
    public void setTransactionIsolation(int level) throws SQLException {
        checkOpen();
        // D1 offers read-your-write via session bookmarks, not JDBC isolation levels.
    }

    @Override
    public int getTransactionIsolation() throws SQLException {
        checkOpen();
        return Connection.TRANSACTION_NONE;
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {
        checkOpen();
        return warnings;
    }

    @Override
    public void clearWarnings() throws SQLException {
        checkOpen();
        warnings = null;
    }

    /** Append a warning to the chain returned by {@link #getWarnings()}. */
    private void addWarning(SQLWarning w) {
        if (warnings == null) {
            warnings = w;
        } else {
            warnings.setNextWarning(w);
        }
    }

    @Override
    public Map<String, Class<?>> getTypeMap() throws SQLException {
        checkOpen();
        return Collections.emptyMap();
    }

    @Override
    public void setTypeMap(Map<String, Class<?>> map) throws SQLException {
        throw new SQLFeatureNotSupportedException("Custom type maps are not supported");
    }

    @Override
    public void setHoldability(int holdability) throws SQLException {
        checkOpen();
        if (holdability != java.sql.ResultSet.CLOSE_CURSORS_AT_COMMIT) {
            throw new SQLFeatureNotSupportedException(
                    "Only CLOSE_CURSORS_AT_COMMIT holdability is supported");
        }
    }

    @Override
    public int getHoldability() throws SQLException {
        checkOpen();
        return java.sql.ResultSet.CLOSE_CURSORS_AT_COMMIT;
    }

    @Override
    public boolean isValid(int timeout) {
        return !closed;
    }

    @Override
    public void setClientInfo(String name, String value) throws SQLClientInfoException {
        // No client-info properties are tracked.
    }

    @Override
    public void setClientInfo(Properties properties) throws SQLClientInfoException {
        // No client-info properties are tracked.
    }

    @Override
    public String getClientInfo(String name) throws SQLException {
        checkOpen();
        return null;
    }

    @Override
    public Properties getClientInfo() throws SQLException {
        checkOpen();
        return new Properties();
    }

    @Override
    public Clob createClob() throws SQLException {
        throw new SQLFeatureNotSupportedException("createClob is not supported");
    }

    @Override
    public Blob createBlob() throws SQLException {
        throw new SQLFeatureNotSupportedException("createBlob is not supported");
    }

    @Override
    public NClob createNClob() throws SQLException {
        throw new SQLFeatureNotSupportedException("createNClob is not supported");
    }

    @Override
    public SQLXML createSQLXML() throws SQLException {
        throw new SQLFeatureNotSupportedException("createSQLXML is not supported");
    }

    @Override
    public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
        throw new SQLFeatureNotSupportedException("createArrayOf is not supported");
    }

    @Override
    public Struct createStruct(String typeName, Object[] attributes) throws SQLException {
        throw new SQLFeatureNotSupportedException("createStruct is not supported");
    }

    @Override
    public void abort(Executor executor) throws SQLException {
        close();
    }

    @Override
    public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException {
        throw new SQLFeatureNotSupportedException(
                "setNetworkTimeout is not supported; use requestTimeoutMillis URL property");
    }

    @Override
    public int getNetworkTimeout() throws SQLException {
        checkOpen();
        return 0;
    }

    // -------------------------------------------------------------- Wrapper

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        if (iface.isInstance(this)) {
            return iface.cast(this);
        }
        throw new SQLException("Not a wrapper for " + iface.getName());
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) {
        return iface.isInstance(this);
    }
}
